name: "🚀 Release: Plugin version"

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  release-branch:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: coffeebeats/godot-infra/package-addon@v1
        with:
          subfolder: phantom_camera
          target-branch: "godot-v4.3"
          godot-editor-version: v4.3-stable
          file-excludes: |
            examples
